//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           7.1.1+g046e9eb0a2
//       
//       Command:
//           LottieGen -Language CSharp -Public -WinUIVersion 3.0 -InputFile ConnectLottie.json
//       
//       Input file:
//           ConnectLottie.json (16327 bytes created 20:03+09:00 May 16 2023)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   246 |
// |--------------------------+-------|
// | Expression animators     |    31 |
// | KeyFrame animators       |    25 |
// | Reference parameters     |    32 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     1 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     1 |
// |--------------------------+-------|
// | ContainerVisuals         |    11 |
// | ShapeVisuals             |     7 |
// |--------------------------+-------|
// | ContainerShapes          |     3 |
// | CompositionSpriteShapes  |    10 |
// |--------------------------+-------|
// | Brushes                  |    13 |
// | Gradient stops           |     2 |
// | CompositionVisualSurface |     4 |
// ------------------------------------
using Microsoft.Graphics.Canvas;
using Microsoft.Graphics.Canvas.Effects;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.Graphics;
using Windows.UI;

namespace AnimatedVisuals
{
    // Name:        24C - Local Account - Other Users
    // Frame rate:  60 fps
    // Frame count: 210
    // Duration:    3500.0 mS
    public sealed class ConnectLottie
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
    {
        // Animation duration: 3.500 seconds.
        internal const long c_durationTicks = 35000000;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new ConnectLottie_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 210d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 210d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class ConnectLottie_AnimatedVisual : Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 35000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            CanvasGeometry _geometry_10;
            CompositionColorBrush _animatedColorBrush_TransparentWhite_to_SemiTransparentWhite;
            CompositionColorBrush _colorBrush_AlmostGainsboro_FFE0DEDC;
            CompositionColorBrush _colorBrush_AlmostLavender_FFDEECF9;
            CompositionColorBrush _colorBrush_Black;
            CompositionColorGradientStop _gradientStop_0_AlmostSlateBlue_FF5B41D2;
            CompositionColorGradientStop _gradientStop_1_AlmostDodgerBlue_FF0078D3;
            CompositionContainerShape _containerShape_0;
            CompositionContainerShape _containerShape_1;
            CompositionContainerShape _containerShape_2;
            CompositionPath _path;
            CompositionPathGeometry _pathGeometry_4;
            CompositionSpriteShape _spriteShape_0;
            ContainerVisual _containerVisual_0;
            ContainerVisual _containerVisual_2;
            ContainerVisual _containerVisual_4;
            ContainerVisual _containerVisual_5;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            CubicBezierEasingFunction _cubicBezierEasingFunction_2;
            CubicBezierEasingFunction _cubicBezierEasingFunction_3;
            CubicBezierEasingFunction _cubicBezierEasingFunction_4;
            CubicBezierEasingFunction _cubicBezierEasingFunction_5;
            CubicBezierEasingFunction _cubicBezierEasingFunction_6;
            ExpressionAnimation _rootProgress;
            InsetClip _insetClip_0;
            ScalarKeyFrameAnimation _scalarAnimation_0_to_1_0;
            ScalarKeyFrameAnimation _scalarAnimation_0_to_1_1;
            ScalarKeyFrameAnimation _scalarAnimation_0_to_1_2;
            ShapeVisual _shapeVisual_2;
            ShapeVisual _shapeVisual_6;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            BooleanKeyFrameAnimation CreateBooleanKeyFrameAnimation(float initialProgress, bool initialValue)
            {
                var result = _c.CreateBooleanKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue);
                return result;
            }

            ColorKeyFrameAnimation CreateColorKeyFrameAnimation(float initialProgress, Color initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateColorKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InterpolationColorSpace = CompositionColorSpace.Rgb;
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector3KeyFrameAnimation CreateVector3KeyFrameAnimation(float initialProgress, Vector3 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector3KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            // - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - Transforms for 24C - Local Account - Other Users - Comped
            BooleanKeyFrameAnimation IsVisibleBooleanAnimation_0()
            {
                // Frame 0.
                var result = CreateBooleanKeyFrameAnimation(0F, false);
                // Frame 18.
                result.InsertKeyFrame(0.0857142881F, true);
                return result;
            }

            // - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - PreComp layer: blue
            // Opacity for layer: Artwork 4
            BooleanKeyFrameAnimation IsVisibleBooleanAnimation_1()
            {
                // Frame 0.
                var result = CreateBooleanKeyFrameAnimation(0F, false);
                // Frame 10.
                result.InsertKeyFrame(0.0476190485F, true);
                return result;
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - Shape tree root for layer: dot
            // - - ShapeGroup: Group 1
            CanvasGeometry Geometry_00()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, 29.5009995F));
                    builder.AddCubicBezier(new Vector2(16.2929993F, 29.5009995F), new Vector2(29.5009995F, 16.2929993F), new Vector2(29.5009995F, 0F));
                    builder.AddCubicBezier(new Vector2(29.5009995F, -16.2929993F), new Vector2(16.2929993F, -29.5009995F), new Vector2(0F, -29.5009995F));
                    builder.AddCubicBezier(new Vector2(-16.2929993F, -29.5009995F), new Vector2(-29.5009995F, -16.2929993F), new Vector2(-29.5009995F, 0F));
                    builder.AddCubicBezier(new Vector2(-29.5009995F, 16.2929993F), new Vector2(-16.2929993F, 29.5009995F), new Vector2(0F, 29.5009995F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - PreComp layer: gray
            // - - - Layer aggregator
            // - -  Offset:<349.754, 235.181>
            CanvasGeometry Geometry_01()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(77.7549973F, 0F));
                    builder.AddCubicBezier(new Vector2(77.7549973F, 42.9430008F), new Vector2(42.9430008F, 77.7549973F), new Vector2(0F, 77.7549973F));
                    builder.AddCubicBezier(new Vector2(-42.9430008F, 77.7549973F), new Vector2(-77.7549973F, 42.9430008F), new Vector2(-77.7549973F, 0F));
                    builder.AddCubicBezier(new Vector2(-77.7549973F, -42.9430008F), new Vector2(-42.9430008F, -77.7549973F), new Vector2(0F, -77.7549973F));
                    builder.AddCubicBezier(new Vector2(42.9430008F, -77.7549973F), new Vector2(77.7549973F, -42.9430008F), new Vector2(77.7549973F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - PreComp layer: gray
            // - - - - Layer aggregator
            // - - ShapeGroup: Group 2 Offset:<349.754, 214.637>
            CanvasGeometry Geometry_02()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, -23.5160007F));
                    builder.AddCubicBezier(new Vector2(-12.9870005F, -23.5160007F), new Vector2(-23.5160007F, -12.9870005F), new Vector2(-23.5160007F, 0F));
                    builder.AddCubicBezier(new Vector2(-23.5160007F, 12.9870005F), new Vector2(-12.9870005F, 23.5160007F), new Vector2(0F, 23.5160007F));
                    builder.AddCubicBezier(new Vector2(12.9870005F, 23.5160007F), new Vector2(23.5160007F, 12.9870005F), new Vector2(23.5160007F, 0F));
                    builder.AddCubicBezier(new Vector2(23.5160007F, -12.9870005F), new Vector2(12.9870005F, -23.5160007F), new Vector2(0F, -23.5160007F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - PreComp layer: gray
            // - - - - Layer aggregator
            // - - ShapeGroup: Group 1 Offset:<349.754, 266.372>
            CanvasGeometry Geometry_03()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-27.6310005F, -18.8129997F));
                    builder.AddCubicBezier(new Vector2(-33.1489983F, -18.8129997F), new Vector2(-37.625F, -14.342F), new Vector2(-37.625F, -8.8210001F));
                    builder.AddLine(new Vector2(-37.625F, -7.05499983F));
                    builder.AddCubicBezier(new Vector2(-37.625F, 1.77600002F), new Vector2(-33.0589981F, 8.38799953F), new Vector2(-26.0550003F, 12.6520004F));
                    builder.AddCubicBezier(new Vector2(-19.1679993F, 16.8449993F), new Vector2(-9.9090004F, 18.8129997F), new Vector2(0F, 18.8129997F));
                    builder.AddCubicBezier(new Vector2(9.9090004F, 18.8129997F), new Vector2(19.1679993F, 16.8449993F), new Vector2(26.0550003F, 12.6520004F));
                    builder.AddCubicBezier(new Vector2(33.0589981F, 8.38799953F), new Vector2(37.625F, 1.77600002F), new Vector2(37.625F, -7.05499983F));
                    builder.AddLine(new Vector2(37.625F, -8.8210001F));
                    builder.AddCubicBezier(new Vector2(37.625F, -14.342F), new Vector2(33.1489983F, -18.8129997F), new Vector2(27.6310005F, -18.8129997F));
                    builder.AddLine(new Vector2(-27.6310005F, -18.8129997F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_04()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-33.4949989F, -81.4469986F));
                    builder.AddCubicBezier(new Vector2(-33.4949989F, -81.4469986F), new Vector2(-42.9230003F, 2.49799991F), new Vector2(-42.9230003F, 2.49799991F));
                    builder.AddCubicBezier(new Vector2(-42.9230003F, 2.49799991F), new Vector2(26.5259991F, 2.44400001F), new Vector2(26.5259991F, 2.44400001F));
                    builder.AddCubicBezier(new Vector2(26.5259991F, 2.44400001F), new Vector2(28.5020008F, -26.0370007F), new Vector2(6.421F, -52.6150017F));
                    builder.AddCubicBezier(new Vector2(-13.3269997F, -76.3850021F), new Vector2(-33.4949989F, -81.4469986F), new Vector2(-33.4949989F, -81.4469986F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - Opacity for layer: Shape Layer 1
            // - - - Transforms: Shape Layer 1 Offset:<308.54102, 304.529>
            // - Path
            CanvasGeometry Geometry_05()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-33.4949989F, -81.4469986F));
                    builder.AddCubicBezier(new Vector2(-33.4949989F, -81.4469986F), new Vector2(-42.9230003F, 2.49799991F), new Vector2(-42.9230003F, 2.49799991F));
                    builder.AddCubicBezier(new Vector2(-42.9230003F, 2.49799991F), new Vector2(28.4449997F, 11.0489998F), new Vector2(28.4449997F, 11.0489998F));
                    builder.AddCubicBezier(new Vector2(28.4449997F, 11.0489998F), new Vector2(28.5020008F, -26.0370007F), new Vector2(6.421F, -52.6150017F));
                    builder.AddCubicBezier(new Vector2(-13.3269997F, -76.3850021F), new Vector2(-33.4949989F, -81.4469986F), new Vector2(-33.4949989F, -81.4469986F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - Opacity for layer: Shape Layer 1
            // - - - Transforms: Shape Layer 1 Offset:<308.54102, 304.529>
            // - Path
            CanvasGeometry Geometry_06()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-35.4459991F, -82.4209976F));
                    builder.AddCubicBezier(new Vector2(-35.4459991F, -82.4209976F), new Vector2(-42.9230003F, 2.49799991F), new Vector2(-42.9230003F, 2.49799991F));
                    builder.AddCubicBezier(new Vector2(-42.9230003F, 2.49799991F), new Vector2(26.4880009F, 2.273F), new Vector2(26.4880009F, 2.273F));
                    builder.AddCubicBezier(new Vector2(26.4880009F, 2.273F), new Vector2(28.5020008F, -26.0370007F), new Vector2(6.421F, -52.6150017F));
                    builder.AddCubicBezier(new Vector2(-13.3269997F, -76.3850021F), new Vector2(-35.4459991F, -82.4209976F), new Vector2(-35.4459991F, -82.4209976F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - Opacity for layer: Shape Layer 1
            // - - - Transforms: Shape Layer 1 Offset:<308.54102, 304.529>
            // - Path
            CanvasGeometry Geometry_07()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-31.4449997F, -80.4240036F));
                    builder.AddCubicBezier(new Vector2(-31.4449997F, -80.4240036F), new Vector2(-42.9230003F, 2.49799991F), new Vector2(-42.9230003F, 2.49799991F));
                    builder.AddCubicBezier(new Vector2(-42.9230003F, 2.49799991F), new Vector2(26.4880009F, 2.273F), new Vector2(26.4880009F, 2.273F));
                    builder.AddCubicBezier(new Vector2(26.4880009F, 2.273F), new Vector2(28.5020008F, -26.0370007F), new Vector2(6.421F, -52.6150017F));
                    builder.AddCubicBezier(new Vector2(-13.3269997F, -76.3850021F), new Vector2(-31.4449997F, -80.4240036F), new Vector2(-31.4449997F, -80.4240036F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - PreComp layer: blue
            // - - - Shape tree root for layer: Artwork 5
            // - -  Offset:<229.512, 318.734>
            CanvasGeometry Geometry_08()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(104.393997F, 0F));
                    builder.AddCubicBezier(new Vector2(104.393997F, 57.6549988F), new Vector2(57.6549988F, 104.393997F), new Vector2(0F, 104.393997F));
                    builder.AddCubicBezier(new Vector2(-57.6549988F, 104.393997F), new Vector2(-104.393997F, 57.6549988F), new Vector2(-104.393997F, 0F));
                    builder.AddCubicBezier(new Vector2(-104.393997F, -57.6549988F), new Vector2(-57.6549988F, -104.393997F), new Vector2(0F, -104.393997F));
                    builder.AddCubicBezier(new Vector2(57.6549988F, -104.393997F), new Vector2(104.393997F, -57.6549988F), new Vector2(104.393997F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - - - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users
            // - Comped
            // - - - - - - - - - - - - - - - - Transforms for 24C - Local Account - Other Users -
            // Comped
            // - - - - - - - - - - - - - - - PreComp layer: blue
            // - - - Shape tree root for layer: Artwork 6
            // - -  Offset:<229.085, 318.324>
            CanvasGeometry Geometry_09()
            {
                var result = Geometry_10().
                    CombineWith(Geometry_10(),
                    Matrix3x2.Identity,
                    CanvasGeometryCombine.Intersect);
                return result;
            }

            // Mask
            CanvasGeometry Geometry_10()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(104.376999F, 0F));
                    builder.AddCubicBezier(new Vector2(104.376999F, 57.6459999F), new Vector2(57.6459999F, 104.376999F), new Vector2(0F, 104.376999F));
                    builder.AddCubicBezier(new Vector2(-57.6459999F, 104.376999F), new Vector2(-104.376999F, 57.6459999F), new Vector2(-104.376999F, 0F));
                    builder.AddCubicBezier(new Vector2(-104.376999F, -57.6459999F), new Vector2(-57.6459999F, -104.376999F), new Vector2(0F, -104.376999F));
                    builder.AddCubicBezier(new Vector2(57.6459999F, -104.376999F), new Vector2(104.376999F, -57.6459999F), new Vector2(104.376999F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_10 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - - - - - PreComp layer: blue
            // - - - Opacity for layer: Artwork 7
            // - -  Offset:<229.512, 318.734>
            CanvasGeometry Geometry_11()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(104.393997F, 0F));
                    builder.AddCubicBezier(new Vector2(104.393997F, 57.6549988F), new Vector2(57.6549988F, 104.393997F), new Vector2(0F, 104.393997F));
                    builder.AddCubicBezier(new Vector2(-57.6549988F, 104.393997F), new Vector2(-101.393997F, 56.6549988F), new Vector2(-101.393997F, -1F));
                    builder.AddCubicBezier(new Vector2(-101.393997F, -58.6549988F), new Vector2(-57.6549988F, -104.393997F), new Vector2(0F, -104.393997F));
                    builder.AddCubicBezier(new Vector2(57.6549988F, -104.393997F), new Vector2(104.393997F, -57.6549988F), new Vector2(104.393997F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - PreComp layer: blue
            // - - - - Opacity for layer: Artwork 4
            // - - ShapeGroup: Group 2 Offset:<229.512, 289.369>
            CanvasGeometry Geometry_12()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, -33.9760017F));
                    builder.AddCubicBezier(new Vector2(-18.7639999F, -33.9760017F), new Vector2(-33.9760017F, -18.7639999F), new Vector2(-33.9760017F, 0F));
                    builder.AddCubicBezier(new Vector2(-33.9760017F, 18.7639999F), new Vector2(-18.7639999F, 33.9760017F), new Vector2(0F, 33.9760017F));
                    builder.AddCubicBezier(new Vector2(18.7639999F, 33.9760017F), new Vector2(33.9760017F, 18.7639999F), new Vector2(33.9760017F, 0F));
                    builder.AddCubicBezier(new Vector2(33.9760017F, -18.7639999F), new Vector2(18.7639999F, -33.9760017F), new Vector2(0F, -33.9760017F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - PreComp layer: blue
            // - - - - Opacity for layer: Artwork 4
            // - - ShapeGroup: Group 1 Offset:<229.512, 364.115>
            CanvasGeometry Geometry_13()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-39.9220009F, -27.1800003F));
                    builder.AddCubicBezier(new Vector2(-47.8950005F, -27.1800003F), new Vector2(-54.3610001F, -20.7210007F), new Vector2(-54.3610001F, -12.7449999F));
                    builder.AddLine(new Vector2(-54.3610001F, -10.1929998F));
                    builder.AddCubicBezier(new Vector2(-54.3610001F, 2.56699991F), new Vector2(-47.7639999F, 12.1190004F), new Vector2(-37.644001F, 18.2800007F));
                    builder.AddCubicBezier(new Vector2(-27.6930008F, 24.3379993F), new Vector2(-14.3170004F, 27.1800003F), new Vector2(0F, 27.1800003F));
                    builder.AddCubicBezier(new Vector2(14.3170004F, 27.1800003F), new Vector2(27.6930008F, 24.3379993F), new Vector2(37.644001F, 18.2800007F));
                    builder.AddCubicBezier(new Vector2(47.7639999F, 12.1190004F), new Vector2(54.3610001F, 2.56699991F), new Vector2(54.3610001F, -10.1929998F));
                    builder.AddLine(new Vector2(54.3610001F, -12.7449999F));
                    builder.AddCubicBezier(new Vector2(54.3610001F, -20.7210007F), new Vector2(47.894001F, -27.1800003F), new Vector2(39.9220009F, -27.1800003F));
                    builder.AddLine(new Vector2(-39.9220009F, -27.1800003F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentWhite_to_SemiTransparentWhite()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF), HoldThenStepEasingFunction());
                // Frame 6.
                // SemiTransparentWhite
                result.InsertKeyFrame(0.0285714287F, Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF), CubicBezierEasingFunction_4());
                return result;
            }

            CompositionColorBrush AnimatedColorBrush_TransparentWhite_to_SemiTransparentWhite()
            {
                if (_animatedColorBrush_TransparentWhite_to_SemiTransparentWhite != null) { return _animatedColorBrush_TransparentWhite_to_SemiTransparentWhite; }
                var result = _animatedColorBrush_TransparentWhite_to_SemiTransparentWhite = _c.CreateColorBrush();
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostGainsboro_FFE0DEDC()
            {
                return (_colorBrush_AlmostGainsboro_FFE0DEDC == null)
                    ? _colorBrush_AlmostGainsboro_FFE0DEDC = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xE0, 0xDE, 0xDC))
                    : _colorBrush_AlmostGainsboro_FFE0DEDC;
            }

            CompositionColorBrush ColorBrush_AlmostLavender_FFDEECF9()
            {
                return (_colorBrush_AlmostLavender_FFDEECF9 == null)
                    ? _colorBrush_AlmostLavender_FFDEECF9 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xDE, 0xEC, 0xF9))
                    : _colorBrush_AlmostLavender_FFDEECF9;
            }

            CompositionColorBrush ColorBrush_Black()
            {
                return (_colorBrush_Black == null)
                    ? _colorBrush_Black = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x00, 0x00, 0x00))
                    : _colorBrush_Black;
            }

            // Stop 0
            CompositionColorGradientStop GradientStop_0_AlmostSlateBlue_FF5B41D2()
            {
                return (_gradientStop_0_AlmostSlateBlue_FF5B41D2 == null)
                    ? _gradientStop_0_AlmostSlateBlue_FF5B41D2 = _c.CreateColorGradientStop(0F, Color.FromArgb(0xFF, 0x5B, 0x41, 0xD2))
                    : _gradientStop_0_AlmostSlateBlue_FF5B41D2;
            }

            // Stop 1
            CompositionColorGradientStop GradientStop_1_AlmostDodgerBlue_FF0078D3()
            {
                return (_gradientStop_1_AlmostDodgerBlue_FF0078D3 == null)
                    ? _gradientStop_1_AlmostDodgerBlue_FF0078D3 = _c.CreateColorGradientStop(1F, Color.FromArgb(0xFF, 0x00, 0x78, 0xD3))
                    : _gradientStop_1_AlmostDodgerBlue_FF0078D3;
            }

            // - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - PreComp layer: gray
            // Layer aggregator
            CompositionContainerShape ContainerShape_0()
            {
                if (_containerShape_0 != null) { return _containerShape_0; }
                var result = _containerShape_0 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // ShapeGroup: Group 2 Offset:<349.754, 214.637>
                shapes.Add(SpriteShape_2());
                // ShapeGroup: Group 1 Offset:<349.754, 266.372>
                shapes.Add(SpriteShape_3());
                return result;
            }

            // - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // Opacity for layer: Shape Layer 1
            CompositionContainerShape ContainerShape_1()
            {
                if (_containerShape_1 != null) { return _containerShape_1; }
                var result = _containerShape_1 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(232.363998F, 327.817993F);
                result.RotationAngleInDegrees = 0.0439999998F;
                // Transforms: Shape Layer 1 Offset:<308.54102, 304.529>
                result.Shapes.Add(SpriteShape_4());
                return result;
            }

            // - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - PreComp layer: blue
            // Opacity for layer: Artwork 4
            CompositionContainerShape ContainerShape_2()
            {
                if (_containerShape_2 != null) { return _containerShape_2; }
                var result = _containerShape_2 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // ShapeGroup: Group 2 Offset:<229.512, 289.369>
                shapes.Add(SpriteShape_8());
                // ShapeGroup: Group 1 Offset:<229.512, 364.115>
                shapes.Add(SpriteShape_9());
                return result;
            }

            // - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - Transforms for 24C - Local Account - Other Users - Comped
            CompositionEffectBrush EffectBrush_0()
            {
                var gaussianBlurEffect = new GaussianBlurEffect();
                gaussianBlurEffect.BlurAmount = 3F;
                gaussianBlurEffect.Source = new CompositionEffectSourceParameter("source");
                var effectFactory = _c.CreateEffectFactory(gaussianBlurEffect);
                var result = effectFactory.CreateBrush();
                result.SetSourceParameter("source", SurfaceBrush_0());
                return result;
            }

            // - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - PreComp layer: blue
            CompositionEffectBrush EffectBrush_1()
            {
                var compositeEffect = new CompositeEffect();
                compositeEffect.Mode = CanvasComposite.DestinationIn;
                compositeEffect.Sources.Add(new CompositionEffectSourceParameter("destination"));
                compositeEffect.Sources.Add(new CompositionEffectSourceParameter("source"));
                var effectFactory = _c.CreateEffectFactory(compositeEffect);
                var result = effectFactory.CreateBrush();
                result.SetSourceParameter("destination", SurfaceBrush_1());
                result.SetSourceParameter("source", SurfaceBrush_3());
                return result;
            }

            // - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - - PreComp layer: blue
            CompositionEffectBrush EffectBrush_2()
            {
                var gaussianBlurEffect = new GaussianBlurEffect();
                gaussianBlurEffect.BlurAmount = 0.600000024F;
                gaussianBlurEffect.Source = new CompositionEffectSourceParameter("source");
                var effectFactory = _c.CreateEffectFactory(gaussianBlurEffect);
                var result = effectFactory.CreateBrush();
                result.SetSourceParameter("source", SurfaceBrush_2());
                return result;
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - PreComp layer: blue
            // - Shape tree root for layer: Artwork 5
            // Offset:<229.512, 318.734>
            CompositionLinearGradientBrush LinearGradientBrush_0()
            {
                var result = _c.CreateLinearGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_AlmostSlateBlue_FF5B41D2());
                colorStops.Add(GradientStop_1_AlmostDodgerBlue_FF0078D3());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(52.4500008F, 90.7440033F);
                result.EndPoint = new Vector2(-51.9609985F, -90.1009979F);
                return result;
            }

            // - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - - - PreComp layer: blue
            // - Opacity for layer: Artwork 7
            // Offset:<229.512, 318.734>
            CompositionLinearGradientBrush LinearGradientBrush_1()
            {
                var result = _c.CreateLinearGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_AlmostSlateBlue_FF5B41D2());
                colorStops.Add(GradientStop_1_AlmostDodgerBlue_FF0078D3());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(52.4500008F, 90.7440033F);
                result.EndPoint = new Vector2(-51.9609985F, -90.1009979F);
                return result;
            }

            CompositionPath Path()
            {
                if (_path != null) { return _path; }
                var result = _path = new CompositionPath(Geometry_04());
                return result;
            }

            // - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - Transforms for 24C - Local Account - Other Users - Comped
            // - Shape tree root for layer: dot
            // ShapeGroup: Group 1
            CompositionPathGeometry PathGeometry_0()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_00()));
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - PreComp layer: gray
            // - Layer aggregator
            // Offset:<349.754, 235.181>
            CompositionPathGeometry PathGeometry_1()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_01()));
            }

            // - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - PreComp layer: gray
            // - - Layer aggregator
            // ShapeGroup: Group 2 Offset:<349.754, 214.637>
            CompositionPathGeometry PathGeometry_2()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_02()));
            }

            // - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - PreComp layer: gray
            // - - Layer aggregator
            // ShapeGroup: Group 1 Offset:<349.754, 266.372>
            CompositionPathGeometry PathGeometry_3()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_03()));
            }

            // - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - Opacity for layer: Shape Layer 1
            // Transforms: Shape Layer 1 Offset:<308.54102, 304.529>
            CompositionPathGeometry PathGeometry_4()
            {
                if (_pathGeometry_4 != null) { return _pathGeometry_4; }
                var result = _pathGeometry_4 = _c.CreatePathGeometry();
                return result;
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - PreComp layer: blue
            // - Shape tree root for layer: Artwork 5
            // Offset:<229.512, 318.734>
            CompositionPathGeometry PathGeometry_5()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_08()));
            }

            // - - - - - - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users -
            // Comped
            // - - - - - - - - - - - - - - Transforms for 24C - Local Account - Other Users -
            // Comped
            // - - - - - - - - - - - - - PreComp layer: blue
            // - Shape tree root for layer: Artwork 6
            // Offset:<229.085, 318.324>
            CompositionPathGeometry PathGeometry_6()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_09()));
            }

            // - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - - - PreComp layer: blue
            // - Opacity for layer: Artwork 7
            // Offset:<229.512, 318.734>
            CompositionPathGeometry PathGeometry_7()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_11()));
            }

            // - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - PreComp layer: blue
            // - - Opacity for layer: Artwork 4
            // ShapeGroup: Group 2 Offset:<229.512, 289.369>
            CompositionPathGeometry PathGeometry_8()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_12()));
            }

            // - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - PreComp layer: blue
            // - - Opacity for layer: Artwork 4
            // ShapeGroup: Group 1 Offset:<229.512, 364.115>
            CompositionPathGeometry PathGeometry_9()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_13()));
            }

            // - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - Transforms for 24C - Local Account - Other Users - Comped
            // Shape tree root for layer: dot
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                if (_spriteShape_0 != null) { return _spriteShape_0; }
                var result = _spriteShape_0 = _c.CreateSpriteShape(PathGeometry_0());
                result.FillBrush = ColorBrush_AlmostGainsboro_FFE0DEDC();
                return result;
            }

            // - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - PreComp layer: gray
            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<349.754, 235.181>
                var geometry = PathGeometry_1();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 349.753998F, 235.181F), ColorBrush_AlmostGainsboro_FFE0DEDC());;
                return result;
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - PreComp layer: gray
            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<349.754, 214.637>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 349.753998F, 214.636993F), AnimatedColorBrush_TransparentWhite_to_SemiTransparentWhite());;
                return result;
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - PreComp layer: gray
            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_3()
            {
                // Offset:<349.754, 266.372>
                var geometry = PathGeometry_3();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 349.753998F, 266.372009F), AnimatedColorBrush_TransparentWhite_to_SemiTransparentWhite());;
                return result;
            }

            // - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - Opacity for layer: Shape Layer 1
            // Path 1
            CompositionSpriteShape SpriteShape_4()
            {
                // Offset:<308.54102, 304.529>
                var geometry = PathGeometry_4();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 308.541016F, 304.528992F), ColorBrush_Black());;
                return result;
            }

            // - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - PreComp layer: blue
            // Shape tree root for layer: Artwork 5
            // Path 1
            CompositionSpriteShape SpriteShape_5()
            {
                // Offset:<229.512, 318.734>
                var geometry = PathGeometry_5();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 229.511993F, 318.734009F), LinearGradientBrush_0());;
                return result;
            }

            // - - - - - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users -
            // Comped
            // - - - - - - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - - - - - - - PreComp layer: blue
            // Shape tree root for layer: Artwork 6
            // ShapeGroup: Group 1
            CompositionSpriteShape SpriteShape_6()
            {
                // Offset:<229.085, 318.324>
                var result = CreateSpriteShape(PathGeometry_6(), new Matrix3x2(1F, 0F, 0F, 1F, 229.085007F, 318.324005F));;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 2.99600005F;
                return result;
            }

            // - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - - PreComp layer: blue
            // Opacity for layer: Artwork 7
            // Path 1
            CompositionSpriteShape SpriteShape_7()
            {
                // Offset:<229.512, 318.734>
                var geometry = PathGeometry_7();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 229.511993F, 318.734009F), LinearGradientBrush_1());;
                return result;
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - PreComp layer: blue
            // - Opacity for layer: Artwork 4
            // Path 1
            CompositionSpriteShape SpriteShape_8()
            {
                // Offset:<229.512, 289.369>
                var geometry = PathGeometry_8();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 229.511993F, 289.368988F), ColorBrush_AlmostLavender_FFDEECF9());;
                return result;
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - PreComp layer: blue
            // - Opacity for layer: Artwork 4
            // Path 1
            CompositionSpriteShape SpriteShape_9()
            {
                // Offset:<229.512, 364.115>
                var geometry = PathGeometry_9();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 229.511993F, 364.11499F), ColorBrush_AlmostLavender_FFDEECF9());;
                return result;
            }

            // - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - Transforms for 24C - Local Account - Other Users - Comped
            CompositionSurfaceBrush SurfaceBrush_0()
            {
                return _c.CreateSurfaceBrush(VisualSurface_0());
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - PreComp layer: blue
            CompositionSurfaceBrush SurfaceBrush_1()
            {
                return _c.CreateSurfaceBrush(VisualSurface_1());
            }

            // - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - - - PreComp layer: blue
            CompositionSurfaceBrush SurfaceBrush_2()
            {
                return _c.CreateSurfaceBrush(VisualSurface_2());
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - PreComp layer: blue
            CompositionSurfaceBrush SurfaceBrush_3()
            {
                return _c.CreateSurfaceBrush(VisualSurface_3());
            }

            // - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - Transforms for 24C - Local Account - Other Users - Comped
            CompositionVisualSurface VisualSurface_0()
            {
                var result = _c.CreateVisualSurface();
                result.SourceVisual = ContainerVisual_4();
                result.SourceSize = new Vector2(552F, 552F);
                return result;
            }

            // - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - PreComp layer: blue
            CompositionVisualSurface VisualSurface_1()
            {
                var result = _c.CreateVisualSurface();
                result.SourceVisual = ContainerVisual_7();
                result.SourceSize = new Vector2(552F, 552F);
                return result;
            }

            // - - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - - - - PreComp layer: blue
            CompositionVisualSurface VisualSurface_2()
            {
                var result = _c.CreateVisualSurface();
                result.SourceVisual = ContainerVisual_8();
                result.SourceSize = new Vector2(552F, 552F);
                return result;
            }

            // - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - PreComp layer: blue
            CompositionVisualSurface VisualSurface_3()
            {
                var result = _c.CreateVisualSurface();
                result.SourceVisual = ContainerVisual_9();
                result.SourceSize = new Vector2(552F, 552F);
                return result;
            }

            // Opacity for layer: 24C - Local Account - Other Users - Comped
            ContainerVisual ContainerVisual_0()
            {
                if (_containerVisual_0 != null) { return _containerVisual_0; }
                var result = _containerVisual_0 = _c.CreateContainerVisual();
                result.CenterPoint = new Vector3(276F, 276F, 0F);
                result.Scale = new Vector3(1F, 1F, 0F);
                // Transforms for 24C - Local Account - Other Users - Comped
                result.Children.InsertAtTop(ContainerVisual_1());
                return result;
            }

            // PreComp layer: 24C - Local Account - Other Users - Comped
            // Transforms for 24C - Local Account - Other Users - Comped
            ContainerVisual ContainerVisual_1()
            {
                var result = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.Size = new Vector2(552F, 552F);
                var children = result.Children;
                // Shape tree root for layer: dot
                children.InsertAtTop(ShapeVisual_0());
                // PreComp layer: gray
                children.InsertAtTop(ContainerVisual_2());
                children.InsertAtTop(SpriteVisual_0());
                // PreComp layer: blue
                children.InsertAtTop(ContainerVisual_5());
                return result;
            }

            // - PreComp layer: 24C - Local Account - Other Users - Comped
            // Transforms for 24C - Local Account - Other Users - Comped
            // Transforms for gray
            ContainerVisual ContainerVisual_2()
            {
                if (_containerVisual_2 != null) { return _containerVisual_2; }
                var result = _containerVisual_2 = _c.CreateContainerVisual();
                result.CenterPoint = new Vector3(349F, 235F, 0F);
                result.Children.InsertAtTop(ContainerVisual_3());
                return result;
            }

            // - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - Transforms for 24C - Local Account - Other Users - Comped
            // PreComp layer: gray
            ContainerVisual ContainerVisual_3()
            {
                var result = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.Size = new Vector2(552F, 552F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_1());
                return result;
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            ContainerVisual ContainerVisual_4()
            {
                if (_containerVisual_4 != null) { return _containerVisual_4; }
                var result = _containerVisual_4 = _c.CreateContainerVisual();
                result.IsVisible = false;
                // Opacity for layer: Shape Layer 1
                result.Children.InsertAtTop(ShapeVisual_2());
                return result;
            }

            // - PreComp layer: 24C - Local Account - Other Users - Comped
            // Transforms for 24C - Local Account - Other Users - Comped
            // Transforms for blue
            ContainerVisual ContainerVisual_5()
            {
                if (_containerVisual_5 != null) { return _containerVisual_5; }
                var result = _containerVisual_5 = _c.CreateContainerVisual();
                result.CenterPoint = new Vector3(232.363998F, 327.817993F, 0F);
                result.RotationAngleInDegrees = 0.0439999998F;
                result.Children.InsertAtTop(ContainerVisual_6());
                return result;
            }

            // - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - Transforms for 24C - Local Account - Other Users - Comped
            // PreComp layer: blue
            ContainerVisual ContainerVisual_6()
            {
                var result = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.Size = new Vector2(552F, 552F);
                var children = result.Children;
                // Shape tree root for layer: Artwork 5
                children.InsertAtTop(ShapeVisual_3());
                children.InsertAtTop(SpriteVisual_1());
                // Opacity for layer: Artwork 4
                children.InsertAtTop(ShapeVisual_6());
                return result;
            }

            // - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - PreComp layer: blue
            ContainerVisual ContainerVisual_7()
            {
                var result = _c.CreateContainerVisual();
                result.BorderMode = CompositionBorderMode.Soft;
                result.Children.InsertAtTop(SpriteVisual_2());
                return result;
            }

            // - - - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - - - - - PreComp layer: blue
            ContainerVisual ContainerVisual_8()
            {
                var result = _c.CreateContainerVisual();
                // Shape tree root for layer: Artwork 6
                result.Children.InsertAtTop(ShapeVisual_4());
                return result;
            }

            // - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - PreComp layer: blue
            ContainerVisual ContainerVisual_9()
            {
                var result = _c.CreateContainerVisual();
                result.BorderMode = CompositionBorderMode.Soft;
                // Opacity for layer: Artwork 7
                result.Children.InsertAtTop(ShapeVisual_5());
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                propertySet.InsertScalar("t0", 0F);
                propertySet.InsertScalar("t1", 0F);
                propertySet.InsertScalar("t2", 0F);
                // PreComp layer: 24C - Local Account - Other Users - Comped
                result.Children.InsertAtTop(ContainerVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.449999988F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return (_cubicBezierEasingFunction_1 == null)
                    ? _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.100000001F, 0F), new Vector2(0.75F, 1F))
                    : _cubicBezierEasingFunction_1;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_2()
            {
                return (_cubicBezierEasingFunction_2 == null)
                    ? _cubicBezierEasingFunction_2 = _c.CreateCubicBezierEasingFunction(new Vector2(0.140000001F, 0F), new Vector2(0.75F, 1F))
                    : _cubicBezierEasingFunction_2;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_3()
            {
                return (_cubicBezierEasingFunction_3 == null)
                    ? _cubicBezierEasingFunction_3 = _c.CreateCubicBezierEasingFunction(new Vector2(0.349999994F, 0F), new Vector2(0.601000011F, 1F))
                    : _cubicBezierEasingFunction_3;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_4()
            {
                return (_cubicBezierEasingFunction_4 == null)
                    ? _cubicBezierEasingFunction_4 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F))
                    : _cubicBezierEasingFunction_4;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_5()
            {
                return (_cubicBezierEasingFunction_5 == null)
                    ? _cubicBezierEasingFunction_5 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0F, 1F))
                    : _cubicBezierEasingFunction_5;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_6()
            {
                return (_cubicBezierEasingFunction_6 == null)
                    ? _cubicBezierEasingFunction_6 = _c.CreateCubicBezierEasingFunction(new Vector2(0.145999998F, 0F), new Vector2(0.75F, 1F))
                    : _cubicBezierEasingFunction_6;
            }

            ExpressionAnimation RootProgress()
            {
                if (_rootProgress != null) { return _rootProgress; }
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            InsetClip InsetClip_0()
            {
                if (_insetClip_0 != null) { return _insetClip_0; }
                var result = _insetClip_0 = _c.CreateInsetClip();
                return result;
            }

            // - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - Opacity for layer: Shape Layer 1
            // - Transforms: Shape Layer 1 Offset:<308.54102, 304.529>
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path(), StepThenHoldEasingFunction());
                // Frame 18.
                result.InsertKeyFrame(0.0857142881F, Path(), HoldThenStepEasingFunction());
                // Frame 28.
                result.InsertKeyFrame(0.13333334F, new CompositionPath(Geometry_05()), CubicBezierEasingFunction_4());
                // Frame 38.
                result.InsertKeyFrame(0.180952385F, new CompositionPath(Geometry_06()), CubicBezierEasingFunction_4());
                // Frame 90.
                result.InsertKeyFrame(0.428571433F, new CompositionPath(Geometry_07()), CubicBezierEasingFunction_4());
                return result;
            }

            // PreComp layer: 24C - Local Account - Other Users - Comped
            // Layer opacity animation
            ScalarKeyFrameAnimation OpacityScalarAnimation_0_to_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.0476190485F, 1F, CubicBezierEasingFunction_4());
                // Frame 199.
                result.InsertKeyFrame(0.947619021F, 1F, CubicBezierEasingFunction_4());
                // Frame 209.
                result.InsertKeyFrame(0.995238066F, 0F, CubicBezierEasingFunction_4());
                return result;
            }

            // - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // Opacity for layer: Shape Layer 1
            // Layer opacity animation
            ScalarKeyFrameAnimation OpacityScalarAnimation_0_to_0p2_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 18.
                result.InsertKeyFrame(0.0857142881F, 0F, HoldThenStepEasingFunction());
                // Frame 24.
                result.InsertKeyFrame(0.114285715F, 0.200000003F, CubicBezierEasingFunction_4());
                return result;
            }

            // - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - PreComp layer: blue
            // Opacity for layer: Artwork 4
            // Layer opacity animation
            ScalarKeyFrameAnimation OpacityScalarAnimation_0_to_0p2_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.0476190485F, 0F, HoldThenStepEasingFunction());
                // Frame 15.
                result.InsertKeyFrame(0.0714285746F, 0.200000003F, CubicBezierEasingFunction_4());
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_0_to_1_0()
            {
                // Frame 0.
                if (_scalarAnimation_0_to_1_0 != null) { return _scalarAnimation_0_to_1_0; }
                var result = _scalarAnimation_0_to_1_0 = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 40.
                result.InsertKeyFrame(0.190476194F, 1.10000002F, CubicBezierEasingFunction_0());
                // Frame 70.
                result.InsertKeyFrame(0.333333343F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_0_to_1_1()
            {
                // Frame 0.
                if (_scalarAnimation_0_to_1_1 != null) { return _scalarAnimation_0_to_1_1; }
                var result = _scalarAnimation_0_to_1_1 = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 35.
                result.InsertKeyFrame(0.166666672F, 1.10000002F, CubicBezierEasingFunction_0());
                // Frame 60.
                result.InsertKeyFrame(0.285714298F, 1F, CubicBezierEasingFunction_2());
                return result;
            }

            // Scale
            ScalarKeyFrameAnimation ScalarAnimation_0_to_1_2()
            {
                // Frame 0.
                if (_scalarAnimation_0_to_1_2 != null) { return _scalarAnimation_0_to_1_2; }
                var result = _scalarAnimation_0_to_1_2 = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 30.
                result.InsertKeyFrame(0.142857149F, 1.04999995F, CubicBezierEasingFunction_0());
                // Frame 55.
                result.InsertKeyFrame(0.261904776F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            ScalarKeyFrameAnimation t0ScalarAnimation_0_to_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 35.
                result.InsertKeyFrame(0.166666657F, 1F, CubicBezierEasingFunction_0());
                // Frame 55.
                result.InsertKeyFrame(0.261904806F, 0F, StepThenHoldEasingFunction());
                // Frame 80.
                result.InsertKeyFrame(0.380952358F, 1F, _c.CreateCubicBezierEasingFunction(new Vector2(0.349999994F, 0F), new Vector2(0.592000008F, 1F)));
                return result;
            }

            ScalarKeyFrameAnimation t1ScalarAnimation_0_to_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 30.
                result.InsertKeyFrame(0.142857134F, 1F, CubicBezierEasingFunction_0());
                return result;
            }

            ScalarKeyFrameAnimation t2ScalarAnimation_0_to_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 40.
                result.InsertKeyFrame(0.190476179F, 1F, CubicBezierEasingFunction_0());
                return result;
            }

            // - PreComp layer: 24C - Local Account - Other Users - Comped
            // Transforms for 24C - Local Account - Other Users - Comped
            // Shape tree root for layer: dot
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(552F, 552F);
                // ShapeGroup: Group 1
                result.Shapes.Add(SpriteShape_0());
                return result;
            }

            // - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - Transforms for 24C - Local Account - Other Users - Comped
            // - PreComp layer: gray
            // Layer aggregator
            ShapeVisual ShapeVisual_1()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(552F, 552F);
                var shapes = result.Shapes;
                // Offset:<349.754, 235.181>
                shapes.Add(SpriteShape_1());
                shapes.Add(ContainerShape_0());
                return result;
            }

            // - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // Shape tree root for layer: Shape Layer 1
            ShapeVisual ShapeVisual_2()
            {
                if (_shapeVisual_2 != null) { return _shapeVisual_2; }
                var result = _shapeVisual_2 = _c.CreateShapeVisual();
                result.Size = new Vector2(552F, 552F);
                result.Shapes.Add(ContainerShape_1());
                return result;
            }

            // - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - Transforms for 24C - Local Account - Other Users - Comped
            // - PreComp layer: blue
            // Shape tree root for layer: Artwork 5
            ShapeVisual ShapeVisual_3()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(552F, 552F);
                // Offset:<229.512, 318.734>
                result.Shapes.Add(SpriteShape_5());
                return result;
            }

            // - - - - - - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - - - - - - PreComp layer: blue
            // Shape tree root for layer: Artwork 6
            ShapeVisual ShapeVisual_4()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(552F, 552F);
                // Offset:<229.085, 318.324>
                result.Shapes.Add(SpriteShape_6());
                return result;
            }

            // - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - PreComp layer: blue
            // Shape tree root for layer: Artwork 7
            ShapeVisual ShapeVisual_5()
            {
                var result = _c.CreateShapeVisual();
                result.Opacity = 0.280000001F;
                result.Size = new Vector2(552F, 552F);
                // Offset:<229.512, 318.734>
                result.Shapes.Add(SpriteShape_7());
                return result;
            }

            // - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - Transforms for 24C - Local Account - Other Users - Comped
            // - PreComp layer: blue
            // Shape tree root for layer: Artwork 4
            ShapeVisual ShapeVisual_6()
            {
                if (_shapeVisual_6 != null) { return _shapeVisual_6; }
                var result = _shapeVisual_6 = _c.CreateShapeVisual();
                result.IsVisible = false;
                result.Size = new Vector2(552F, 552F);
                result.Shapes.Add(ContainerShape_2());
                return result;
            }

            // - PreComp layer: 24C - Local Account - Other Users - Comped
            // Transforms for 24C - Local Account - Other Users - Comped
            SpriteVisual SpriteVisual_0()
            {
                var result = _c.CreateSpriteVisual();
                result.Size = new Vector2(552F, 552F);
                result.Brush = EffectBrush_0();
                return result;
            }

            // - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - Transforms for 24C - Local Account - Other Users - Comped
            // - PreComp layer: blue
            SpriteVisual SpriteVisual_1()
            {
                var result = _c.CreateSpriteVisual();
                result.Size = new Vector2(552F, 552F);
                result.Brush = EffectBrush_1();
                return result;
            }

            // - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - - - - PreComp layer: blue
            SpriteVisual SpriteVisual_2()
            {
                var result = _c.CreateSpriteVisual();
                result.Size = new Vector2(552F, 552F);
                result.Brush = EffectBrush_2();
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - Transforms for 24C - Local Account - Other Users - Comped
            // - Shape tree root for layer: dot
            // ShapeGroup: Group 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(266.753998F, 477.425995F), HoldThenStepEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 40.
                result.InsertExpressionKeyFrame(0.190476179F, "Pow(1-_.t2,3)*Vector2(266.754,477.426)+(3*Square(1-_.t2)*_.t2*Vector2(143,350))+(3*(1-_.t2)*Square(_.t2)*Vector2(226.588,150.519))+(Pow(_.t2,3)*Vector2(226.588,150.519))", StepThenHoldEasingFunction());
                // Frame 40.
                result.InsertKeyFrame(0.190476194F, new Vector2(226.587997F, 150.518997F), StepThenHoldEasingFunction());
                // Frame 70.
                result.InsertKeyFrame(0.333333343F, new Vector2(226.761002F, 159F), CubicBezierEasingFunction_2());
                // Frame 90.
                result.InsertKeyFrame(0.428571433F, new Vector2(226.753998F, 157.425995F), CubicBezierEasingFunction_3());
                return result;
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - PreComp layer: gray
            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 20F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.285714298F, new Vector2(0F, 0F), CubicBezierEasingFunction_5());
                return result;
            }

            // - - - - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - Opacity for layer: Shape Layer 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(15.6359997F, 155.182007F), HoldThenStepEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 30.
                result.InsertExpressionKeyFrame(0.142857134F, "Pow(1-_.t1,3)*Vector2(15.636,155.182)+(3*Square(1-_.t1)*_.t1*Vector2(-41.364,70.18201))+(3*(1-_.t1)*Square(_.t1)*Vector2(-4.364,-3.318))+(Pow(_.t1,3)*Vector2(-4.364,-3.318))", StepThenHoldEasingFunction());
                // Frame 30.
                result.InsertKeyFrame(0.142857149F, new Vector2(-4.36399984F, -3.31800008F), StepThenHoldEasingFunction());
                // Frame 55.
                result.InsertKeyFrame(0.261904776F, new Vector2(-4.43200016F, 7.18499994F), CubicBezierEasingFunction_6());
                // Frame 80.
                result.InsertExpressionKeyFrame(0.380952358F, "Pow(1-_.t0,3)*Vector2(-4.432,7.185)+(3*Square(1-_.t0)*_.t0*Vector2(-4.432,7.185))+(3*(1-_.t0)*Square(_.t0)*Vector2(-4.205,4.776))+(Pow(_.t0,3)*Vector2(-4.364,5.182))", StepThenHoldEasingFunction());
                // Frame 80.
                result.InsertKeyFrame(0.380952388F, new Vector2(-4.36399984F, 5.18200016F), StepThenHoldEasingFunction());
                return result;
            }

            // - - - - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - - - - Transforms for 24C - Local Account - Other Users - Comped
            // - - - PreComp layer: blue
            // - Opacity for layer: Artwork 4
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_3()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 20F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.0476190485F, new Vector2(0F, 20F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.285714298F, new Vector2(0F, 0F), CubicBezierEasingFunction_5());
                return result;
            }

            // - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - Transforms for 24C - Local Account - Other Users - Comped
            // PreComp layer: gray
            // Offset
            Vector3KeyFrameAnimation OffsetVector3Animation_0()
            {
                // Frame 0.
                var result = CreateVector3KeyFrameAnimation(0F, new Vector3(-50F, 210F, 0F), HoldThenStepEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 35.
                result.InsertExpressionKeyFrame(0.166666657F, "Pow(1-_.t0,3)*Vector3(-50,210,0)+(3*Square(1-_.t0)*_.t0*Vector3(36.689,141.602,0))+(3*(1-_.t0)*Square(_.t0)*Vector3(0.679,-9.286,0))+(Pow(_.t0,3)*Vector3(0.679,-9.286,0))", StepThenHoldEasingFunction());
                // Frame 35.
                result.InsertKeyFrame(0.166666672F, new Vector3(0.67900002F, -9.28600025F, 0F), StepThenHoldEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.285714298F, new Vector3(0.0309999995F, 1.72399998F, 0F), CubicBezierEasingFunction_2());
                // Frame 85.
                result.InsertKeyFrame(0.40476191F, new Vector3(0F, 0F, 0F), CubicBezierEasingFunction_3());
                return result;
            }

            // - - PreComp layer: 24C - Local Account - Other Users - Comped
            // - Transforms for 24C - Local Account - Other Users - Comped
            // PreComp layer: blue
            // Offset
            Vector3KeyFrameAnimation OffsetVector3Animation_1()
            {
                // Frame 0.
                var result = CreateVector3KeyFrameAnimation(0F, new Vector3(15.6359997F, 155.182007F, 0F), HoldThenStepEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 30.
                result.InsertExpressionKeyFrame(0.142857134F, "Pow(1-_.t1,3)*Vector3(15.636,155.182,0)+(3*Square(1-_.t1)*_.t1*Vector3(-41.364,70.18201,0))+(3*(1-_.t1)*Square(_.t1)*Vector3(-4.364,-3.318,0))+(Pow(_.t1,3)*Vector3(-4.364,-3.318,0))", StepThenHoldEasingFunction());
                // Frame 30.
                result.InsertKeyFrame(0.142857149F, new Vector3(-4.36399984F, -3.31800008F, 0F), StepThenHoldEasingFunction());
                // Frame 55.
                result.InsertKeyFrame(0.261904776F, new Vector3(-4.43200016F, 7.18499994F, 0F), CubicBezierEasingFunction_6());
                // Frame 80.
                result.InsertExpressionKeyFrame(0.380952358F, "Pow(1-_.t0,3)*Vector3(-4.432,7.185,0)+(3*Square(1-_.t0)*_.t0*Vector3(-4.432,7.185,0))+(3*(1-_.t0)*Square(_.t0)*Vector3(-4.205,4.776,0))+(Pow(_.t0,3)*Vector3(-4.364,5.182,0))", StepThenHoldEasingFunction());
                // Frame 80.
                result.InsertKeyFrame(0.380952388F, new Vector3(-4.36399984F, 5.18200016F, 0F), StepThenHoldEasingFunction());
                return result;
            }

            // PreComp layer: 24C - Local Account - Other Users - Comped
            // Offset
            Vector3KeyFrameAnimation OffsetVector3Animation_2()
            {
                // Frame 0.
                var result = CreateVector3KeyFrameAnimation(0F, new Vector3(0F, 60F, 0F), HoldThenStepEasingFunction());
                // Frame 30.
                result.InsertKeyFrame(0.142857149F, new Vector3(0F, 0F, 0F), _c.CreateCubicBezierEasingFunction(new Vector2(0.239999995F, 0F), new Vector2(0.360000014F, 1F)));
                // Frame 180.
                result.InsertKeyFrame(0.857142866F, new Vector3(0F, 0F, 0F), _c.CreateCubicBezierEasingFunction(new Vector2(0.239999995F, 0.239999995F), new Vector2(0.75999999F, 0.75999999F)));
                // Frame 209.
                result.InsertKeyFrame(0.995238066F, new Vector3(0F, -60F, 0F), _c.CreateCubicBezierEasingFunction(new Vector2(1F, 0F), new Vector2(0.833000004F, 0.833000004F)));
                return result;
            }

            internal ConnectLottie_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(552F, 552F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                StartProgressBoundAnimation(_animatedColorBrush_TransparentWhite_to_SemiTransparentWhite, "Color", ColorAnimation_TransparentWhite_to_SemiTransparentWhite(), RootProgress());
                StartProgressBoundAnimation(_containerShape_0, "Offset", OffsetVector2Animation_1(), RootProgress());
                StartProgressBoundAnimation(_containerShape_1, "Scale.X", ScalarAnimation_0_to_1_2(), RootProgress());
                StartProgressBoundAnimation(_containerShape_1, "Scale.Y", ScalarAnimation_0_to_1_2(), RootProgress());
                StartProgressBoundAnimation(_containerShape_1, "Offset", OffsetVector2Animation_2(), RootProgress());
                StartProgressBoundAnimation(_containerShape_2, "Offset", OffsetVector2Animation_3(), RootProgress());
                StartProgressBoundAnimation(_pathGeometry_4, "Path", PathKeyFrameAnimation_0(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_0, "Scale.X", ScalarAnimation_0_to_1_0(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_0, "Scale.Y", ScalarAnimation_0_to_1_0(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_0, "Offset", OffsetVector2Animation_0(), RootProgress());
                StartProgressBoundAnimation(_containerVisual_0, "Opacity", OpacityScalarAnimation_0_to_0(), RootProgress());
                StartProgressBoundAnimation(_containerVisual_0, "Offset", OffsetVector3Animation_2(), RootProgress());
                StartProgressBoundAnimation(_containerVisual_2, "Scale.X", ScalarAnimation_0_to_1_1(), RootProgress());
                StartProgressBoundAnimation(_containerVisual_2, "Scale.Y", ScalarAnimation_0_to_1_1(), RootProgress());
                StartProgressBoundAnimation(_containerVisual_2, "Offset", OffsetVector3Animation_0(), RootProgress());
                StartProgressBoundAnimation(_containerVisual_4, "IsVisible", IsVisibleBooleanAnimation_0(), RootProgress());
                StartProgressBoundAnimation(_containerVisual_5, "Scale.X", ScalarAnimation_0_to_1_2(), RootProgress());
                StartProgressBoundAnimation(_containerVisual_5, "Scale.Y", ScalarAnimation_0_to_1_2(), RootProgress());
                StartProgressBoundAnimation(_containerVisual_5, "Offset", OffsetVector3Animation_1(), RootProgress());
                StartProgressBoundAnimation(_root.Properties, "t0", t0ScalarAnimation_0_to_1(), RootProgress());
                StartProgressBoundAnimation(_root.Properties, "t1", t1ScalarAnimation_0_to_1(), RootProgress());
                StartProgressBoundAnimation(_root.Properties, "t2", t2ScalarAnimation_0_to_1(), RootProgress());
                StartProgressBoundAnimation(_shapeVisual_2, "Opacity", OpacityScalarAnimation_0_to_0p2_0(), RootProgress());
                StartProgressBoundAnimation(_shapeVisual_6, "Opacity", OpacityScalarAnimation_0_to_0p2_1(), RootProgress());
                StartProgressBoundAnimation(_shapeVisual_6, "IsVisible", IsVisibleBooleanAnimation_1(), RootProgress());
            }

            public void DestroyAnimations()
            {
                _animatedColorBrush_TransparentWhite_to_SemiTransparentWhite.StopAnimation("Color");
                _containerShape_0.StopAnimation("Offset");
                _containerShape_1.StopAnimation("Scale.X");
                _containerShape_1.StopAnimation("Scale.Y");
                _containerShape_1.StopAnimation("Offset");
                _containerShape_2.StopAnimation("Offset");
                _pathGeometry_4.StopAnimation("Path");
                _spriteShape_0.StopAnimation("Scale.X");
                _spriteShape_0.StopAnimation("Scale.Y");
                _spriteShape_0.StopAnimation("Offset");
                _containerVisual_0.StopAnimation("Opacity");
                _containerVisual_0.StopAnimation("Offset");
                _containerVisual_2.StopAnimation("Scale.X");
                _containerVisual_2.StopAnimation("Scale.Y");
                _containerVisual_2.StopAnimation("Offset");
                _containerVisual_4.StopAnimation("IsVisible");
                _containerVisual_5.StopAnimation("Scale.X");
                _containerVisual_5.StopAnimation("Scale.Y");
                _containerVisual_5.StopAnimation("Offset");
                _root.Properties.StopAnimation("t0");
                _root.Properties.StopAnimation("t1");
                _root.Properties.StopAnimation("t2");
                _shapeVisual_2.StopAnimation("Opacity");
                _shapeVisual_6.StopAnimation("Opacity");
                _shapeVisual_6.StopAnimation("IsVisible");
            }

        }
    }
}
